#!/usr/bin/env bash
set -eE -o pipefail

export  stderrPipeDebug="awk \"{print \\\"\\\\033[00m\$(date +%Y-%m-%dT%H:%M:%S%z) [  debug] \\\"\\\$0\\\"\\\\033[0m\\\"}\" /dev/stdin 1>&2"
export stderrPipeNotice="awk \"{print \\\"\\\\033[01m\$(date +%Y-%m-%dT%H:%M:%S%z) [ notice] \\\"\\\$0\\\"\\\\033[0m\\\"}\" /dev/stdin 1>&2"
export  stderrPipeError="awk \"{print \\\"\\\\033[31m\$(date +%Y-%m-%dT%H:%M:%S%z) [  error] \\\"\\\$0\\\"\\\\033[0m\\\"}\" /dev/stdin 1>&2"
export     stderrPipeOK="awk \"{print \\\"\\\\033[32m\$(date +%Y-%m-%dT%H:%M:%S%z) [     ok] \\\"\\\$0\\\"\\\\033[0m\\\"}\" /dev/stdin 1>&2"
export   stderrPipeWarn="awk \"{print \\\"\\\\033[33m\$(date +%Y-%m-%dT%H:%M:%S%z) [warning] \\\"\\\$0\\\"\\\\033[0m\\\"}\" /dev/stdin 1>&2"
export   stderrPipeInfo="awk \"{print \\\"\\\\033[34m\$(date +%Y-%m-%dT%H:%M:%S%z) [   info] \\\"\\\$0\\\"\\\\033[0m\\\"}\" /dev/stdin 1>&2"

# const
declare -r PROG_NAME=unity3d-installer                                               && export PROG_NAME
declare -r UNITY_DOWNLOAD_ARCHIVE_URL=https://unity3d.com/get-unity/download/archive && export UNITY_DOWNLOAD_ARCHIVE_URL

# function 1
selectWritableDir () { for path in "$@"; do [ ! -w "${path}" ] || { echo -n "${path}"; return 0; }; done }
checkSupportOS () { if ! uname -s | grep -q Linux; then echo "OS not supported." | sh -c "${stderrPipeError:?}"; exit 1; fi; }
resolveDependencies () {
  if command -v apt-get 1>/dev/null; then
    if ! command -v apt-file 1>/dev/null; then
      echo "apt-file command is required." | sh -c "${stderrPipeError:?}"
      exit 1
    fi
  else
    echo "OS not supported." | sh -c "${stderrPipeError:?}"
    exit 1
  fi
}

# var 1
separator=$(printf '\t')                                       && declare -r Separator="${separator:?}" && export Separator
progDir=$(cd "$(dirname "$0")" && pwd || exit 1)               && declare -r ProgDir="${progDir:?}"     && export ProgDir

# var 2
csvStoreDir=$(selectWritableDir "${HOME:?}" "${ProgDir:?}" /tmp) && declare -r CSVStoreDir="${csvStoreDir:?}"                              && export CSVStoreDir
: noop                                                           && declare -r UnitySetupURLCSVFile="${CSVStoreDir:?}/.${PROG_NAME:?}.csv" && export UnitySetupURLCSVFile
setupsDir=$(selectWritableDir "${HOME:?}" "${ProgDir:?}" /tmp)   && declare -r SetupsDir="${setupsDir:?}"                                  && export SetupsDir



function CreateOrUpdateUnitySetupURLCSVFile () { (
  # [ fource option ] || [ can't read ${UnitySetupURLCSVFile:?} ] || [ ${UnitySetupURLCSVFile:?} is empty ]
  if [[ $* =~ .*-f.*|.*--fource.* ]] || [[ ! -r ${UnitySetupURLCSVFile:?} ]] || [[ ! -s ${UnitySetupURLCSVFile:?} ]]; then
    echo "Generating a UnitySetup URL csv file as ${UnitySetupURLCSVFile:?} ..." | sh -c "${stderrPipeInfo:?}"
    csvData=$(
      # CSV header
      printf "%s${Separator:?}%s${Separator:?}%s\n" "version" "status" "url"
      # CSV data
      curl -LsS "${UNITY_DOWNLOAD_ARCHIVE_URL:?}" \
        | grep "href=\"unityhub://" \
        | sed "s|^.*\"unityhub://\([^/]*\)/\([^\"]*\)\".*$|https://download.unity3d.com/download_unity/\2/UnitySetup-\1|" \
        | while read -r url; do
            printf "%s${Separator:?}%s${Separator:?}%s\n" "$(printf "%s" "${url}" | sed "s|.*/UnitySetup-||")" "$(curl -ILsS -o /dev/null -w "%{http_code}" "${url:?}")" "${url:?}"
          done \
        | if [[ $* =~ .*-v.*|.*--verbose.* ]]; then tee /dev/stderr; else cat; fi
    )
    echo "${csvData:?}" >"${UnitySetupURLCSVFile:?}"
  fi
  echo "UnitySetup URL csv file was saved as ${UnitySetupURLCSVFile:?}" | sh -c "${stderrPipeInfo:?}"
)}



function InstallUnity () { (
  # [ doesn't have install subcommand and version ]
  if [[ ! $* =~ install.*[[:blank:]]*[[:blank:]]+[^\.]+\.[^\.]+\.[^\.]+ ]]; then
    echo "Specify Unity version." | sh -c "${stderrPipeError:?}"
    exit 1
  fi
  # [ can't read ${UnitySetupURLCSVFile:?} ] || [ ${UnitySetupURLCSVFile:?} is empty ]
  if [[ ! -r ${UnitySetupURLCSVFile:?} ]] || [[ ! -s ${UnitySetupURLCSVFile:?} ]]; then
    CreateOrUpdateUnitySetupURLCSVFile "$@" --verbose
  fi
  # vars
  status=200
  specified_version=$(printf '%s' "$*" | sed "s@install.*[[:blank:]]*[[:blank:]][[:blank:]]*\([^\.][^\.]*\.[^\.][^\.]*\.[^\.][^\.]*\).*@\1@")
  specified_version_escaped_regex=${specified_version//\./\\.}
  csvRow=$(grep "^${specified_version_escaped_regex}${Separator:?}${status:?}${Separator:?}" "${UnitySetupURLCSVFile:?}")
  if [[ -z "${csvRow:?}" ]]; then
    echo "Specify the version of Unity that can be installed." | sh -c "${stderrPipeError:?}"
    exit 1
  fi
  url=$(echo "${csvRow:?}" | awk -F"${Separator:?}" "\$0=\$3")
  setupFileName=$(basename "${url:?}")
  defaultDownloadDir="${SetupsDir:?}/${setupFileName:?}" && mkdir -p "${defaultDownloadDir:?}"
  defaultDownloadPath="${defaultDownloadDir:?}/${setupFileName:?}"
  echo "Download ${url:?} as ${defaultDownloadPath:?}" | sh -c "${stderrPipeInfo:?}"
  sh -cx "curl -LR ${url:?} -z ${defaultDownloadPath:?} -o ${defaultDownloadPath:?} && chmod +x ${defaultDownloadPath:?}"

  while ! error=$("${defaultDownloadPath:?}" --help 2>&1); do
    if [[ ${error} ]]; then
      # output error
      echo "${error:?}" | sh -c "${stderrPipeInfo:?}"
      # install lib
      libName="$(echo "${error:?}" | awk -F: "\$0=\$3" | tr -d "[:blank:]")"
      echo "Install ${libName:?}" | sh -c "${stderrPipeInfo:?}"
      result=$(sudo -E sh -cx "apt-file search ${libName:?}")
      # output result
      echo "${result:?}" | sh -c "${stderrPipeInfo:?}"
      # output result
      echo "${result:?}" | awk -F: "\$0=\$1" | while read -r deb; do
        if ! dpkg -l | grep -Eq "ii[[:blank:]]+${package:?}"; then
          sudo -E sh -cx "apt-get -y install ${package:?}"
          continue
        fi
      done
      #echo "${result:?}" | grep x86_64-linux-gnu | awk -F: "\$0=\$1" | sort -u | while read -r package; do
      #  sudo -E sh -cx "apt-get -y install ${package:?}"
      #done
    else
      break
    fi
  done
)}



function ListInstallableVersions () { (
  if [[ ! -r ${UnitySetupURLCSVFile:?} ]] || [[ ! -s ${UnitySetupURLCSVFile:?} ]]; then
    echo "UnitySetup URL csv file not found." | sh -c "${stderrPipeWarn:?}"
  fi
  versions=$(
    grep -E "[^${Separator:?}]+${Separator:?}200${Separator:?}[^${Separator:?}]+" "${UnitySetupURLCSVFile:?}" \
      | awk -F"${Separator:?}" "{print \$1}"
  )
  if [[ $* =~ .*-1.*|.*--one-column.* ]]; then
    echo "${versions}"
  elif command -v column 1>/dev/null; then
    echo "${versions}" | column
  else
    echo "${versions}"
  fi
)}



function Usage () { (
  cat << USAGE
${PROG_NAME:?} is a tool for helping to install Unity to Linux.

Usage:

	${PROG_NAME:?} <command> [arguments]

The commands are:

        init        create or update UnitySetup URL csv file as ${UnitySetupURLCSVFile:?}

                    arguments
                        -f, --fource
                            fource update
                        -v, --verbose
                            display verbose info.

        install     install specified version Unity

                    arguments
                        <version>
                            Unity version

        list        list installable Unity versions

                    arguments
                        -1, --one-column
                            If you want to output a single column, add this option

USAGE
)}



function main () {
  checkSupportOS
  resolveDependencies
  case "$1" in
  init)
    CreateOrUpdateUnitySetupURLCSVFile "$@"
    ;;
  install)
    InstallUnity "$@"
    ;;
  list|list-versions)
    ListInstallableVersions "$@"
    ;;
  *)
    Usage
    ;;
  esac
} && main "$@"
